version: "3"
services:
  db:
    image: mysql:5.7
    container_name: heydb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Abc.123
      MYSQL_DATABASE: heydb
      MYSQL_PASSWORD: Abc.123
    ports:
      - "3306:3306"

  web:
    image: php:8.0-apache
    container_name: heybackend
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "4000:80"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: heyphpmyadmin
    depends_on:
      - db
    external_links:
      - db:mysql
    ports:
      - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Abc.123
      MYSQL_ROOT_PASSWORD: Abc.123
      PMA_HOST: db